-- 코드를 입력하세요
SELECT date_format(Z.SALES_DATE, '%Y-%m-%d') as SALES_DATE, Z.PRODUCT_ID, Z.USER_ID, Z.SALES_AMOUNT
FROM (
    select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
    union ALL
    select SALES_DATE, PRODUCT_ID, null, SALES_AMOUNT FROM OFFLINE_SALE
) Z
WHERE Z.SALES_DATE >= '2022-03-01' and Z.SALES_DATE < '2022-04-01'
ORDER BY Z.SALES_DATE ASC, Z.PRODUCT_ID ASC, Z.USER_ID ASC