-- 코드를 입력하세요

SELECT USER_ID, NICKNAME, concat(CITY, ' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) as '전체주소', 
    CONCAT(SUBSTRING(TLNO, 1, 3),'-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) as '전화번호'
FROM(
SELECT WRITER_ID
FROM USED_GOODS_BOARD A
group by WRITER_ID
Having count(*) >= 3) K, USED_GOODS_USER A
WHERE K.WRITER_ID = A.USER_ID
ORDER BY USER_ID DESC