-- 코드를 입력하세요

SELECT Z.ANIMAL_TYPE, Z.NAME, Z.SEX_UPON_INTAKE
FROM (SELECT ANIMAL_TYPE, NAME, SEX_UPON_INTAKE, ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
union all
SELECT ANIMAL_TYPE, 'No name' as NAME, SEX_UPON_INTAKE, ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL) Z
ORDER BY Z.ANIMAL_ID