-- 코드를 입력하세요
# PRODUCT / OFFLINE_SALE
# SELECT PR.PRODUCT_CODE, SUM(PR.PRICE) AS SALES
# FROM PRODUCT PR JOIN OFFLINE_SALE OFF ON PR.PRODUCT_ID = OFF.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SUM(PRICE) DESC, PR.PRODUCT_CODE ASC

# SELECT *
# FROM PRODUCT

# SELECT *
# FROM OFFLINE_SALE

# SELECT PR.PRODUCT_CODE, SUM(PR.PRICE) AS SALES
# FROM PRODUCT PR JOIN OFFLINE_SALE OFF ON PR.PRODUCT_ID = OFF.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SUM(PRICE) DESC, PR.PRODUCT_CODE ASC

SELECT PRODUCT_CODE, SUM(PR.PRICE * OFF.SALES_AMOUNT) AS SALES
FROM PRODUCT PR JOIN OFFLINE_SALE OFF ON PR.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC

