-- 코드를 입력하세요

# SELECT *
# FROM ICECREAM_INFO

# SELECT *
# FROM FIRST_HALF

SELECT IC.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER)
FROM ICECREAM_INFO IC JOIN FIRST_HALF FH ON IC.FLAVOR = FH.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY SUM(FH.TOTAL_ORDER)