-- 코드를 입력하세요

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY START_DATE

SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE 
    C.CAR_ID = H.CAR_ID 
    and C.CAR_TYPE = '세단' 
    and date_format(H.START_DATE, '%Y-%m-%d') >= '2022-10-01' 
    and date_format(H.START_DATE, '%Y-%m-%d') < '2022-11-01'
ORDER BY C.CAR_ID DESC
